device: cuda
root_dir: /data1/statduck/exp1_result_fans_500epochs
seed: 1
dataset:
  root: ../Data
  name: null
  sem_name: null
  env2_name: null
  env2_sem_name: null
  env2_base_version: null
  splits: [ 0.8, 0.2, 0.0 ]
  k_fold: 1
  shuffle_train: true
  loss: default
  scale: default
  num_samples: 50000
  base_version: null
  type: torch
  use_edge_attr: false
  external_dag_path: /data1/statduck/data/nodes_50/ER/adj_22.npy
  external_data_path: /data1/statduck/data/nodes_50/ER/data_env1_22.npy
  env2_external_data_path: /data1/statduck/data/nodes_50/ER/data_env2_22.npy
  test_data_path: /data1/statduck/data_small/nodes_50/ER/data_env1_22.npy
  env2_test_data_path: /data1/statduck/data_small/nodes_50/ER/data_env2_22.npy
  metadata_path: /data1/statduck/data/nodes_50/ER/metadata_22.json
model:
  name: causal_nf
  layer_name: nsf
  dim_inner: [32, 32, 32]
  num_layers: 1
  init: None
  act: elu
  adjacency: true
  base_to_data: false
  base_distr: normal
  learn_base: false
  plot: false
train:
  max_epochs: 500
  regularize: false
  kl: forward
  batch_size: 512
  num_workers: 0
  limit_train_batches: None
  limit_val_batches: None
  max_time: 00:10:00:00
  inference_mode: false
optim:
  optimizer: adam
  base_lr: 0.01
  beta_1: 0.9
  beta_2: 0.999
  momentum: 0.0
  weight_decay: 0.0
  scheduler: plateau
  mode: min
  factor: 0.95
  patience: 60
  cooldown: 0
